version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ratownictwo_postgres
    environment:
      POSTGRES_USER: ratownictwo_user
      POSTGRES_PASSWORD: gZiMiGf2buBbpIBJzWdogiJVACXzNobcDCwwmxxSgVI
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: ratownictwo_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
